// MIT License
#ifndef VECTORPDF_ACCESSIBILITYGLOBAL_H
#define VECTORPDF_ACCESSIBILITYGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VECTORPDF_ACCESSIBILITY_LIBRARY)
#  define VECTORPDF_ACCESSIBILITY_EXPORT Q_DECL_EXPORT
#else
#  define VECTORPDF_ACCESSIBILITY_EXPORT Q_DECL_IMPORT
#endif

#endif // VECTORPDF_ACCESSIBILITYGLOBAL_H
