// MIT License
#ifndef VECTORPDF_WORKFLOWGLOBAL_H
#define VECTORPDF_WORKFLOWGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VECTORPDF_WORKFLOW_LIBRARY)
#  define VECTORPDF_WORKFLOW_EXPORT Q_DECL_EXPORT
#else
#  define VECTORPDF_WORKFLOW_EXPORT Q_DECL_IMPORT
#endif

#endif // VECTORPDF_WORKFLOWGLOBAL_H
