// MIT License
#ifndef VECTORPDF_SCANTOOLSGLOBAL_H
#define VECTORPDF_SCANTOOLSGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VECTORPDF_SCANTOOLS_LIBRARY)
#  define VECTORPDF_SCANTOOLS_EXPORT Q_DECL_EXPORT
#else
#  define VECTORPDF_SCANTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // VECTORPDF_SCANTOOLSGLOBAL_H
